-- schema.sql
-- Create shipments & incidents tables with a VECTOR column for embeddings

-- Shipments (toy schema for demo)
CREATE TABLE shipments (
  shipment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_code       VARCHAR2(40),
  origin_city      VARCHAR2(80),
  destination_city VARCHAR2(80),
  departed_at      TIMESTAMP,
  arrived_at       TIMESTAMP,
  status           VARCHAR2(30)
);

-- Incident reports that we will embed
CREATE TABLE shipment_incidents (
  incident_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id   NUMBER REFERENCES shipments(shipment_id),
  occurred_at   TIMESTAMP,
  severity      VARCHAR2(20),
  description   CLOB,
  -- The embedding column (adjust dimension to your model; 1536 for many OpenAI models)
  embedding     VECTOR(1536)
);

-- Create a vector index for fast ANN search
-- The exact syntax/parameters vary by Oracle version. This uses generic notation.
CREATE VECTOR INDEX incidents_vec_idx ON shipment_incidents (embedding);
