-- vector_update.sql
-- Example: attach precomputed embeddings (dummy vector literals for illustration).
-- Replace with embeddings generated by your model of choice.
-- VECTOR literal uses an array-like syntax in recent Oracle versions; adjust to your environment.

-- Example single-row update (illustrative numbers)
UPDATE shipment_incidents
SET embedding = VECTOR(0.01, 0.02, 0.03 /* ... up to dimension ... */)
WHERE incident_id = 1;

-- Repeat per row or use a PL/SQL block to batch updates.
